# Functions_with_exceptions_py